version: '2'
services:
  personal_blog:
    build: ./wordpress
    container_name: personal_blog
    links:
      - personal_blog_db:mysql
    env_file:
      - .env
    ports:
      - 46396:80
    volumes:
      - ./wordpress/src:/var/www/html
  personal_blog_db:
    build: ./database
    container_name: personal_blog_db
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/mysql